<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://www.axway.com/mappingServices/project" createdBy="akesharwani" lastModifiedBy="akesharwani" checksumTest="true" creationDate="05/09/2018 13:24:03 +0530" engineType="DML" lastModifiedDate="14/09/2018 15:23:42 +0530" engineVersion="2.1">
   <mappingInformations>
      <mappingInformation state="Inactive" path="Mapping Flows/ClaimToDB.dmlflw"/>
   </mappingInformations>
</project>